death:
  pvp:
    default: ' &fwas killed by '
    projectile: ' &fwas shot by '
  pve:
    default: ' &fdied in a freak accident.'
    custom: ' &fwas killed by admin abuse. Grab the pitchforks!'
    block_explosion: ' &fdied from an exploding block.'
    contact: ' &ftried to hug a cactus.'
    dragon_breath: ' &fgave a breath check to a dragon.'
    drowning: ' &fforgot they didn''t have underwater breathing.'
    entity_attack: ' &fgot beaten up by a zombie.'
    entity_explosion: ' &fdidn''t notice the creeper.'
    fall: ' &ffell off a cliff.'
    falling_block: ' &fhad an anvil land on their head.'
    fire: ' &fstood in the flames.'
    fire_tick: ' &fgot slow roasted.'
    lava: ' &fswam in lava.'
    lightning: '&fgot struck by lightning!'
    poison: ' &fwas poisoned.'
    projectile: ' &ftook an arrow to the knee.'
    starvation: ' &fstarved to death.'
    suffocation: ' &fbreathed in too much sand.'
    suicide: ' &fdidn''t call 1-800-273-8255.'
    thorns: ' &fwore a crown of thorns.'
    void: ' &fwent flying with the elder dragon.'
    wither: ' &fwithered away.'
tag:
  time: 30
  distance: 10
brewing:
  speed: 5
furnace:
  speed: 5
looting-buffer: 2
enderchest-disabled: false
gapple:
  time: 30
spawn-mobs: false
barrier:
  refresh:
    ticks: 2
  view-distance: 8
  max-distance: 32
regions:
  max-name: 16
enderpearl:
  time: 15
enchantment-limiter:
  ARROW_DAMAGE: 4
  ARROW_FIRE: 0
  ARROW_INFINITE: -1
  ARROW_KNOCKBACK: 1
  DAMAGE_ALL: 1
  DAMAGE_ARTHROPODS: -1
  DAMAGE_UNDEAD: -1
  DIG_SPEED: -1
  DURABILITY: -1
  FIRE_ASPECT: 0
  KNOCKBACK: 1
  LOOT_BONUS_BLOCKS: -1
  LOOT_BONUS_MOBS: -1
  LUCK: -1
  LURE: -1
  OXYGEN: -1
  PROTECTION_ENVIRONMENTAL: 2
  PROTECTION_EXPLOSIONS: -1
  PROTECTION_FALL: -1
  PROTECTION_FIRE: -1
  PROTECTION_PROJECTILE: -1
  SILK_TOUCH: -1
  THORNS: 0
  WATER_WORKER: -1
unrepairable-lore-line: "&cUnrepairable"
allowed_potions:
  HEAL:
    level: 2
    extended: false
  FIRE_RESISTANCE:
    level: 1
    extended: true
  INVISIBILITY:
    level: 1
    extended: false
  POISON:
    level: 2
    extended: true
  SPEED:
    level: 2
    extended: true
  SLOW:
    level: 2
    extended: true
findore:
  - 'diamond_ore'
  - 'emerald_ore'
crowbar:
  uses: 6
  spawner:
    cost: 6
  frame:
    cost: 1
logout:
  time: 30
blocked:
  - FURNACE
  - CHEST
  - TRAPPED_CHEST
  - BEACON
  - DISPENSER
  - DROPPER
  - HOPPER
  - WORKBENCH
  - ENCHANTMENT_TABLE
  - ENDER_CHEST
  - ANVIL
  - BED_BLOCK
  - FENCE_GATE
  - SPRUCE_FENCE_GATE
  - BIRCH_FENCE_GATE
  - ACACIA_FENCE_GATE
  - JUNGLE_FENCE_GATE
  - DARK_OAK_FENCE_GATE
  - IRON_DOOR_BLOCK
  - WOODEN_DOOR
  - SPRUCE_DOOR
  - BIRCH_DOOR
  - JUNGLE_DOOR
  - ACACIA_DOOR
  - DARK_OAK_DOOR
  - WOOD_BUTTON
  - STONE_BUTTON
  - TRAP_DOOR
  - IRON_TRAPDOOR
  - DIODE_BLOCK_OFF
  - DIODE_BLOCK_ON
  - REDSTONE_COMPARATOR_OFF
  - REDSTONE_COMPARATOR_ON
  - FENCE
  - SPRUCE_FENCE
  - BIRCH_FENCE
  - JUNGLE_FENCE
  - DARK_OAK_FENCE
  - ACACIA_FENCE
  - NETHER_FENCE
  - BREWING_STAND
  - CAULDRON
  - SIGN_POST
  - WALL_SIGN
  - SIGN
  - LEVER
  - BLACK_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - LIME_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - PINK_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - RED_SHULKER_BOX
  - SILVER_SHULKER_BOX
  - WHITE_SHULKER_BOX
  - YELLOW_SHULKER_BOX
classes:
  archer:
    increase-percent: 1.20
    hit-time: 30
    cooldown: 10
    effects:
      SUGAR:
        effect: SPEED
        click:
          amplifier: 3
          duration: 7
          energy: 20
          self: true
          faction: false
          allies: false
          other: false
      FEATHER:
        effect: JUMP
        click:
          amplifier: 6
          duration: 8
          energy: 20
          self: true
          faction: false
          allies: false
          other: false
        hold:
          amplifier: 1
          duration: 7
          self: true
          faction: true
          allies: false
          other: false
  bard:
    range: 10
    hold-duration: 7
    effects:
      SUGAR:
        effect: SPEED
        click:
          amplifier: 2
          duration: 7
          energy: 20
          self: true
          faction: true
          allies: false
          other: false
        hold:
          amplifier: 1
          duration: 7
          self: false
          faction: true
          allies: false
          other: false
      BLAZE_POWDER:
        effect: INCREASE_DAMAGE
        click:
          amplifier: 1
          duration: 7
          energy: 45
          self: true
          faction: true
          allies: false
          other: false
        hold:
          amplifier: 0
          duration: 7
          self: false
          faction: true
          allies: false
          other: false
      IRON_INGOT:
        effect: DAMAGE_RESISTANCE
        click:
          amplifier: 1
          duration: 5
          energy: 40
          self: true
          faction: true
          allies: false
          other: false
        hold:
          amplifier: 0
          duration: 6
          self: false
          faction: true
          allies: false
          other: false
      SPIDER_EYE:
        effect: WITHER
        click:
          amplifier: 0
          duration: 6
          energy: 45
          self: true
          faction: false
          allies: false
          other: true
      GHAST_TEAR:
        effect: REGENERATION
        click:
          amplifier: 1
          duration: 3
          energy: 40
          self: true
          faction: true
          allies: false
          other: false
        hold:
          amplifier: 0
          duration: 5
          self: false
          faction: true
          allies: false
          other: true
      FEATHER:
        effect: JUMP
        click:
          amplifier: 6
          duration: 8
          energy: 30
          self: true
          faction: true
          allies: false
          other: false
        hold:
          amplifier: 3
          duration: 7
          self: true
          faction: true
          allies: false
          other: true
      MAGMA_CREAM:
        effect: FIRE_RESISTANCE
        click:
          amplifier: 0
          duration: 180
          energy: 30
          self: true
          faction: true
          allies: false
          other: false
        hold:
          amplifier: 0
          duration: 8
          self: true
          faction: true
          allies: false
          other: false
    rouge-finder:
      range: 80
      remainder: 30
  rogue:
    duration: 20
    invisible-length: 120
    uninvis-range: 10
    uninvis-timer: 30
    effects:
      SUGAR:
        effect: SPEED
        click:
          amplifier: 5
          duration: 5
          energy: 20
          cooldown: 30
      FEATHER:
        effect: JUMP
        click:
          amplifier: 6
          duration: 7
          energy: 20
          cooldown: 15
      IRON_INGOT:
        effect: DAMAGE_RESISTANCE
        click:
          amplifier: 2
          duration: 6
          energy: 20
          cooldown: 30
  miner:
    diamonds:
      100:
        - SPEED-2
      250:
        - SPEED-2
        - DAMAGE_RESISTANCE-1
      500:
        - SPEED-3
        - DAMAGE_RESISTANCE-1
      1000:
        - SPEED-3
        - DAMAGE_RESISTANCE-1
        - FAST_DIGGING-3
      2500:
        - SPEED-3
        - DAMAGE_RESISTANCE-2
        - FAST_DIGGING-3
spawn:
  x: 0
  y: 100
  z: 0
  yaw: 0
  pitch: 0
  world: world
factions:
  stuck:
    time: 3600
  claim_wand:
    name: '§6§lClaim Wand'
    lore:
      - '§eLeft-Click for point one.'
      - '§eRight-Click for point two.'
  claims:
    cost:
      block: 0.25
      existing_scale: 500