name: HCFCore
version: 0.1
main: me.borawski.hcf.Core
description: Core system
dependencies: [WorldEdit, WorldGuard]

commands:
  achievement:
    usage: /<command>
    description: List all aquired achievements.
  ban:
    usage: /<command>
    description: Ban a user from the server.
  crowbar:
    usage: /<command>
    description: Spawn in a new crowbar.
  enderchest:
    usage: /<command>
    description: Toggle the ender chest.
  friends:
    usage: /<command>
    description: Manage the safe zone regions.
  fstat:
    usage: /<command>
    description: View your player stats.
  info:
    usage: /<command>
    description: Get a user's information.
  manual:
    usage: /<command>
    description: Opens a manual.
  hcfreload:
    usage: /<command>
    description: Reloads the lang file.
  settings:
    usage: /<command>
    description: Change your VIP settings.
  lives:
    usage: /<command>
    description: Add or remove lives.
  rank:
    usage: /<command>
    description: View your rank or manage others.
  hregion:
    usage: /<command>
    description: Manage the protection regions.
  setend:
    usage: /<command>
    description: Sets the end spawn.