name: HCFCore
version: 0.1
main: me.borawski.hcf.Core
description: Core system
dependencies: [WorldEdit, WorldGuard]

commands:
     factions:
          aliases: [f]
     info:
          description: Admin tool to look at player data
          aliases: [pi, i, pinfo]
     ban:
          description: Self explanatory
     rank:
          description: For admins to check/change ranks
     friend:
          description: Add friends!
     achievements:
          description: Check your achievements
          aliases: [ac, a]
     settings:
          description: Change your settings!
          aliases: [s, set]
     manual:
     fverbose:
     fstat:
     crowbar:
     enderchest:
     lives:
     setendspawn:
     setendexit:
     pvptimer:
     koth:
     season:
         aliases: [si, sinfo, pvpinfo, leaderboard, score, scoreboard]
